local M = {
    CLIENT_MSG_IDS = {
        CREATE_PLAYER = "CREATE_PLAYER",
        LEAVE_ROOM = "NOT_GS_LEAVE_ROOM",
        PLAYER_COMMANDS = "NOT_GS_PLAYER_COMMANDS",
    },
    MSG_IDS = {
        GAME_JOIN = "GAME_JOIN",
        GAME_LEAVE = "GAME_LEAVE",
        PLAYER_LEAVE_ROOM = "PLAYER_LEAVE_ROOM",
        CONNECT_OTHER = "CONNECT_OTHER",
        CONNECT_SELF = "CONNECT_SELF",
        DISCONNECT = "DISCONNECT",
        CONNECT_ME = "CONNECT_ME",
        GAME_PRE_START = "GAME_PRE_START",
        GAME_START = "GAME_START",
        GAME_OVER = "GAME_OVER",
        ONLINE = "ONLINE",
        LATENCY = "LATENCY"
    }
}

return M
