version: "3.7"
volumes:
  data:
services:
  escape_from_massacre:
    platform: linux/x86_64
    container_name: escape_from_massacre
    build:
      context: .
      args:
        BIND_ADDRESS: ${BIND_ADDRESS}
        CERT: ${CERT}
        CERT_KEY: ${CERT_KEY}
    ports:
      - 4433:4433
      - "194.195.87.104:5002:5002"
