local MainState = require "src.main_state"
local debugUtils = require "src.utils.debug-utils"

local log = debugUtils.createLog("[level]").log
local MSG_GROUPS = MainState.MSG_GROUPS

function init(self)
	log("level init", msg.url())
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") and message.other_group == hash("bullet") then
		go.delete(message.other_id)
	end
end
