---
--- Generated by Luanalysis
--- Created by romanchekashov.
--- DateTime: 9/15/23 1:11 PM
---
local M = {
    COLORS = {
        GREEN = vmath.vector4(46 / 255, 209 / 255, 153 / 255, 0),
        RED = vmath.vector4(209 / 255, 46 / 255, 102 / 255, 0),
    }
}

return M
