server:
  port: 5001
  ssl:
    certificate: /Users/romanchekashov/workspace/defold/MultiplayerGames/webtransport-py/certificate/fullchain.pem
    certificate-private-key: /Users/romanchekashov/workspace/defold/MultiplayerGames/webtransport-py/certificate/privkey.pem

spring:
  application:
    name: game
  config:
    #    import: optional:secret.properties
    import: optional:file:.env.local[.properties]

logging:
  level:
    root: INFO
  file:
    name: log/sample-webflux-websocket-netty.log

sample:
  path: /
  send-interval: 500

START_GAME_SERVER_SHELL_SCRIPT: ../run_game_server_x86_64_macos.sh
